export enum TrackStatus {
  UNCONCERNED = "UNCONCERNED",
  PRE_INBOUND = "PRE_INBOUND",
  INBOUND = "INBOUND",
  ACCEPTED = "ACCEPTED",
  INTRUDER = "INTRUDER",
  INBOUND_OFFER = "INBOUND_OFFER",
  OUTBOUND_OFFER = "OUTBOUND_OFFER",
}
